# Change these first
owner: WPContained # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Brabys
    url: https://www.brabys.com/za/plumbers
  - name: Tyremart
    url: https://www.tyremart.co.za
  - name: brabysebooks
    url: http://www.brabysebooks.co.za
  - name: brabysproducts
    url: http://www.brabysproducts.co.za
  - name: admin.goldenspoon.co.za
    url: https://admin.goldenspoon.co.za
  - name: bronberg.goldenspoon.co.za
    url: https://bronberg.goldenspoon.co.za
  - name: Funfwd
    url: https://funfwd.com
  - name: Belgotex API
    url: https://files.belgotex.co.za/monitor.txt
  - name: Glassfinder
    url: https://glassfinder.pgsmartglass.co.za
  - name: pay.dev.swiffy.co.za
    url: https://pay.dev.swiffy.co.za
  - name: Swiffy Pay
    url: https://pay.swiffy.co.za
  - name: TM Promo
    url: https://promo.tyremart.co.za
  - name: Swiffy USSD Push
    url: https://ussdpush.swiffy.co.za/ping.txt
  - name: Ananzi
    url: https://www.ananzi.co.za
  - name: Brabys Listing
    url: https://www.brabys.com/za/kwazulu-natal/pinetown/maps/brabys
  - name: Brabys Listing AMP
    url: https://www.brabys.com/za/kwazulu-natal/pinetown/maps/brabys?amp=1
  - name: brabys search
    url: https://www.brabys.com/za/plumbers
  - name: brabys search amp
    url: https://www.brabys.com/za/plumbers?amp=1
  - name: everything47
    url: https://www.everything47.com
  - name: swiffy site
    url: https://www.swiffy.co.za
  - name: yellowpages.bw
    url: https://www.yellowpages.bw
  - name: yellowpages.bw search
    url: https://www.yellowpages.bw/results/category/Plumbers    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
  robotsText: "User-agent: * \n Disallow: /"
  user-agent: WPContained/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
